### ISSUE TITLE
Please include a copy of the license in the root of the repository

### ISSUE THREAD

**Issue by eriknstr** [XProger/OpenLara#28]
Your README mentions that OpenLara is released under the terms of the 2-Clause BSD license.

Including a copy of the license in a file called LICENSE will allow GitHub to add which license is used for the repo to the info bar of the repository.

Furthermore including a copy of the license and setting the copyright year(s), author name(s) and author e-mail address(es) (or website(s) if you don't want to reveal your e-mail address) in it will allow your users to live up to the license, which has the following among its requirements:

>1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
>
>2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

**Comment by DrMcCoy** [comment]
Also, you *can't* make the code BSD 2-clause, because you include and directly link in LGPLv2.1+ code, namely [minimp3](https://github.com/XProger/OpenLara/blob/master/src/libs/minimp3/minimp3.cpp) (which is based on ffmpeg). As such, you're currently in violation of the LGPL 2.1.

Essentially, as it currently is, your code would have to be licensed either:
- LGPL 2.1
- LGPL 3 (allowed through the "or later" clause in minimp3)
- GPL 2.1 (explicitly allowed by the LGPL 2.1)
- GPL 3 (combination of "or later" with explit LGPL 2.1 -> GPL 2.1 upgrade)
- AGPL 3 (By way of the GPL 3 path, because the GPL 3 has an explict upgrade to AGPL 3)

Since this is the LGPL, not the GPL proper, if you want to keep the BSD 2-clause license, what you can do is this:
- Compile minimp3 into a dynamically linked library (.so on Unixoids, .dll on Windows)
- Dynamically link this library with your main executable

Alternatively, you could
1) Dynamically link to libmpg123, also LGPL
2) Look for a different MP3 decoder. I'm unfortunately not aware of any stb-style librally licensed, single-file mp3 decoders.

(The commonly used MAD library would be out, because it's licensed GPL, so no difference in your situation here)

**Comment by eriknstr** [comment]
@DrMcCoy IANAL but [someone on StackOverflow](http://stackoverflow.com/a/10179181) linked to https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic and said regarding statically linking LGPL code that as long as "everything that allow the user to relink the application with a different version of the LGPL source code" is provided, you are not in violation of LGPL.

Personally I avoid GPL and LGPL code to the greatest extent possible because of such legal uncertainties.

**Comment by DrMcCoy** [comment]
@eriknstr, huh, interesting, I hadn't heard about that. You learn something new every day, thanks! :)

Seems like this is a relatively recent addition to the FAQ too: checking with the wayback machine, that entry arrived some time between 2013-06-02 and 2013-07-04.

But yeah, as per the FAQ and my layperson understanding (IANAL as well), this code here seems fine, then. I'm withdrawing my objection from above.

> it's troublesome because it limits what can be done with OpenLara as opposed to what could be done without the restrictions of the LGPL source code

Yeah, you have to watch that no code wanders from these files into the rest of the codebase. Having it link dynamically could be a kind of "moat" helping to prevent that. Still, that's a secondary/minor quibble.

**Comment by mudlord** [comment]
Do any of the games use MP3? Why not adding dr_flac?

**Comment by XProger** [comment]
@mudlord Applied to OpenLara project: size (for streaming from web or disk drive), quality (enough for 1996 year game) and soundtracks availability in the web.
