### ISSUE TITLE
APK -- [Android]

### ISSUE THREAD

**Issue by MarshMeadow** [XProger/OpenLara#456]
The apk is not working, I have android 10, and it keeps crashing...

**Comment by XProger** [comment]
@MarshMeadow hi, can you copy-paste the text from readme.txt here?

**Comment by marianob85** [comment]
Same here. Galaxy S23+, Android 13. App crash right after lunch.

**Comment by XProger** [comment]
@marianob85 hi, the same question as above, can you copy-paste the readme.txt text from the archive?

**Comment by marianob85** [comment]
Yes. I've already play on this game on my old phone. So I know, how to proceed. It seems that the problem was with me, because as first I uploaded all necessary files and then install and run the game :/ Don't know why, but removing all assets, kill app, run it with crash and then upload the assets solved problem. So my apologies. Was my fault.

**Comment by DRSDavidSoft** [comment]
Since nobody copy-pasted the instructions from README.txt per @XProger's request, I thought I'd do so. Thank you for such an amazing project!

```
Instruction:
STEP 1: Install OpenLara.apk and run it, it'll crash, it's ok
STEP 2: Let's assume that you own the original game, so download and unzip ("extract here") these archives into "/Android/data/com.xproger.openlara/files/"
	data http://xproger.info/projects/OpenLara/files/TR1_data.7z
	audio http://xproger.info/projects/OpenLara/files/TR1_audio.7z
STEP 3: Run OpenLara again and enjoy the game!
```
